- name: Printing facts
  hosts: localhost
  connection: local
  tasks:
    - name: Print ansible_facts
      ansible.builtin.debug:
        msg: "{{ ansible_facts }}"

    - name: Print mounts and memory
      ansible.builtin.debug:
        msg: "{{ ansible_facts['mounts']['dns'] }}"
