- name: Jinja template example
  hosts: localhost
  connection: local
  vars:
    student: { name: "Murugan", course: "DevOps" }
  tasks:
    - name: Copying the files
      ansible.builtin.copy:
        src: sample.txt
        dest: /tmp/h1.txt
