- name: Variables from Inventory
  hosts: TEST
  tasks:
    - name: Print URL
      ansible.builtin.debug: #Used to print the value of the variable URL assigned to this host in the inventory file
        msg: "URL - {{ URL }}, COMPONENT - {{ COMPONENT }}"

- name: Variables from Playbook
  hosts: TEST
  vars:
    type: t3.micro
  vars_files:
    - vars.yaml #Importing variables from an external file
  tasks:
    - name: Print variables from playbook
      ansible.builtin.debug:
        msg: "Type - {{ type }}, IP_ADDRESS - {{ IP_ADDRESS }}"

- name: Variables from Roles #Variables can also be defined in roles and they will be available to the tasks within that role. The variables defined in the role will override any variables defined in the playbook or inventory file if there is a conflict.
  hosts: TEST
  roles:
    - sample
